# Generated by Django 4.2.6 on 2023-12-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0002_alter_mensajeria_receptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria',
            name='contenido',
            field=models.TextField(),
        ),
    ]
