# Generated by Django 4.2.6 on 2023-12-02 15:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0003_alter_mensajeria_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
