# Generated by Django 4.2.6 on 2023-11-26 00:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_empleo', models.CharField(max_length=100)),
                ('descripcion_empleo', ckeditor.fields.RichTextField()),
                ('empresa', models.CharField(max_length=50)),
                ('fecha_publicacion_empleo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
