# Generated by Django 4.2.6 on 2023-11-24 00:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleos',
            name='descripcion_empleo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
