# Generated by Django 4.2.6 on 2023-10-25 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posteos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_posteo', models.CharField(max_length=100)),
                ('descripcion_posteo', models.CharField(max_length=120)),
                ('imagen_posteo', models.ImageField(upload_to='')),
                ('redaccion_posteo', models.TextField()),
                ('fecha_posteo', models.DateTimeField(auto_now_add=True)),
                ('autor_posteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
