# Generated by Django 4.2.6 on 2023-10-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posteos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_posteo', models.CharField(max_length=100)),
                ('redaccion_posteo', models.CharField(max_length=3000)),
                ('fecha_posteo', models.DateTimeField()),
                ('autor_posteo', models.CharField(max_length=50)),
            ],
        ),
    ]
