# Generated by Django 4.2.6 on 2023-10-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteos',
            name='area_poste',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='posteos',
            name='fecha_posteo',
            field=models.DateField(null=True),
        ),
    ]
