# Generated by Django 4.2.6 on 2023-10-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_blog', '0002_alter_posteos_fecha_posteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos',
            name='fecha_posteo',
            field=models.CharField(max_length=8),
        ),
    ]
