# Generated by Django 4.2.6 on 2023-10-21 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_blog', '0003_rename_area_poste_posteos_area_posteo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosteoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_posteo', models.CharField(max_length=12)),
                ('redaccion_posteo', models.TextField()),
                ('autor_posteo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PosteosTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_posteo', models.CharField(max_length=12)),
                ('titulo_posteo', models.CharField(max_length=100)),
                ('description_posteo', models.CharField(max_length=120)),
                ('fecha_posteo', models.DateField(verbose_name=datetime.datetime(2023, 10, 21, 19, 44, 32, 711765))),
            ],
        ),
        migrations.DeleteModel(
            name='Posteos',
        ),
    ]
