# Generated by Django 4.2.6 on 2023-10-22 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_blog', '0004_posteodetalle_posteostarjeta_delete_posteos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteostarjeta',
            name='fecha_posteo',
            field=models.DateField(verbose_name=datetime.datetime(2023, 10, 22, 0, 25, 29, 76726)),
        ),
    ]
