# Generated by Django 4.2.6 on 2023-10-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_blog', '0007_alter_posteos_imagen_posteo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteos',
            name='imagen_posteo',
        ),
    ]
