# Generated by Django 4.2.6 on 2023-10-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_blog', '0008_remove_posteos_imagen_posteo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusquedaPosteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busqueda', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='posteos',
            name='titulo_posteo',
            field=models.CharField(max_length=30),
        ),
    ]
