# Generated by Django 4.2.6 on 2023-10-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_blog', '0009_busquedaposteo_alter_posteos_titulo_posteo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusquedaPosteo',
        ),
        migrations.AlterField(
            model_name='posteos',
            name='titulo_posteo',
            field=models.CharField(max_length=100),
        ),
    ]
