# Generated by Django 4.2.6 on 2023-10-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_blog', '0010_delete_busquedaposteo_alter_posteos_titulo_posteo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programacion', models.CharField(max_length=50)),
                ('robotica', models.CharField(max_length=50)),
                ('matematicas', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='posteos',
            name='categoria_posteo',
            field=models.ManyToManyField(to='inicio_blog.categorias'),
        ),
    ]
