# Generated by Django 4.2.6 on 2023-10-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_blog', '0011_categorias_posteos_categoria_posteo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteos',
            name='categoria_posteo',
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.AddField(
            model_name='posteos',
            name='categoria_posteo',
            field=models.CharField(choices=[('Programacion', 'Programación'), ('Robotica', 'Robótica'), ('Matematicas', 'Matemáticas')], default='Programacion', max_length=20),
        ),
    ]
