# Generated by Django 4.2.6 on 2023-10-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_blog', '0012_remove_posteos_categoria_posteo_delete_categorias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos',
            name='categoria_posteo',
            field=models.CharField(choices=[('Programacion', 'Programación'), ('Robotica', 'Robótica'), ('Matematicas', 'Matemáticas')], default='Elige una categoria para tu Post', max_length=20),
        ),
    ]
