# Generated by Django 4.2.6 on 2023-10-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_blog', '0013_alter_posteos_categoria_posteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos',
            name='categoria_posteo',
            field=models.CharField(choices=[('Programacion', 'Programación'), ('Robotica', 'Robótica'), ('Matematicas', 'Matemáticas')], default='Programacion', max_length=20),
        ),
    ]
