# Generated by Django 4.2.6 on 2023-11-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_blog', '0016_alter_posteos_descripcion_posteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos',
            name='descripcion_posteo',
            field=models.CharField(max_length=120),
        ),
    ]
