# Generated by Django 4.2.6 on 2023-11-18 14:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_blog', '0018_alter_posteos_descripcion_posteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos',
            name='redaccion_posteo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
