# Generated by Django 4.2.6 on 2023-11-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_blog', '0019_alter_posteos_redaccion_posteo'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteos',
            name='imagen_posteo',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_posteos'),
        ),
    ]
