# Generated by Django 4.2.6 on 2023-11-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_blog', '0021_remove_posteos_imagen_posteo'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteos',
            name='imagen_posteo',
            field=models.ImageField(blank=True, null=True, upload_to='img_card_blog'),
        ),
    ]
