# Generated by Django 4.2.6 on 2023-11-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_blog', '0022_posteos_imagen_posteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos',
            name='imagen_posteo',
            field=models.ImageField(blank=True, null=True, upload_to='img_card_blog/'),
        ),
    ]
