# Generated by Django 4.2.6 on 2023-12-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_perfil', '0002_rename_datosextrasperfil_datosextrasusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosextrasusuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/'),
        ),
    ]
