# Generated by Django 4.2.6 on 2023-12-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_perfil', '0003_datosextrasusuario_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextrasusuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
